spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  application:
    name: taco-cloud

  thymeleaf:
    cache: false

  datasource:
    generate-unique-name: false
    name: tacocloud
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
taco:
  order:
    pageSize: 20


---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/tacocloud
    username: testuser
    password: test
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: create
